spring.application.name=vehicle-tracking-api
# Tomcat Sunucu Portu (Varsay?lan 8080'dir, çak??mamas? için 8081 yapabilirsin)
server.port=8080

# PostgreSQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_tracking_db
spring.datasource.username=postgres
spring.datasource.password=789654123As

# JPA ve Hibernate Ayarlar?
# 'update' seçene?i, biz Java'da Entity class'? olu?turdu?umuzda veritaban?nda tabloyu otomatik açar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true